### ISSUE TITLE
[Bug] Unable to merge PRs. GitHub Action fails due to path being too long

### ISSUE THREAD

**Issue by sruke** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#3050]
**Issue Description:**

When running GitHub Actions for Pull Requests, the workflow fails during tests due to excessively long paths.

**Environment:**
- Microsoft.IdentityModel Version: Latest

**Steps to Reproduce:**
- NA

**Expected Behavior:**
- GitHub Action for PRs should pass without errors.

**Actual Behavior:**
- GitHub Action fails due to path length limitations.

**Possible Solutions:**
- Support long paths
- Identify a way to use a shorter path

**Additional Context/Logs/Screenshots:**
- Open GitHub Issue: [Support for custom or shorter base workdir paths · Issue #1676 · actions/runner](https://github.com/actions/runner/issues/1676)

**Attempted Solutions:**
1. Set path in`actions/checkout`:
   - Did not work. Configured path added as a suffix to the repository name instead of replacing it.
   
2. Updating `GITHUB_WORKSPACE` to point to a shorter path did not work.
   - Tried the following:
     ```yaml
     - name: Set shorter workspace path
       run: echo "workspace=/tmp/short-path" >> $GITHUB_ENV
     ```

3. Checked if long paths are enabled on the machine:
   - The following command returned 1, indicating long paths are enabled:
     ```yaml
     - name: Check LongPathsEnabled
       run: |
         (Get-ItemProperty "HKLM:System\CurrentControlSet\Control\FileSystem").LongPathsEnabled
     ```
